### ISSUE TITLE
gnuradio 3.7.8 installed with pybombs

### ISSUE THREAD

**Issue by ran2** [trendmicro/ais#3]
The new pull request on gr-aistx of gnuradio 3.7 (https://github.com/dadopap/ais) still not be compiled. Error log as below:

~/ais/gr-aistx/build$ make
[ 20%] Built target gnuradio-AISTX
[ 33%] Built target test-AISTX
[ 40%] Built target _AISTX_swig_swig_tag
[ 46%] Swig source
/home/ran2/ais/gr-aistx/swig/AISTX_swig.i:5: Error: Unable to find 'gnuradio.i'
swig/CMakeFiles/_AISTX_swig.dir/build.make:56: recipe for target 'swig/AISTX_swigPYTHON_wrap.cxx' failed
make[2]: **\* [swig/AISTX_swigPYTHON_wrap.cxx] Error 1
CMakeFiles/Makefile2:213: recipe for target 'swig/CMakeFiles/_AISTX_swig.dir/all' failed
make[1]: **\* [swig/CMakeFiles/_AISTX_swig.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by coshub82** [comment]
Hi, 

I have exactly the same issue, and doesn't know how to solve it. 
Have you manage to resolve the Unable to find 'gnuradio.i' ?
Thanks

**Comment by prisemut** [comment]
Same issue here, I did not figure out how to change the swig path in cmake. 

However the following work around works: 
copy all .i files from the gnuradio installation into the projects build/swig directory 
copy gnuradio_swig_bug_workaround.h into the same directory 
In Ubuntu 16.04 do this: 

cp /usr/include/gnuradio/swig/*.i swig/
cp /usr/include/gnuradio/swig/gnuradio_swig_bug_workaround.h  swig/
make

**Comment by dadopap** [comment]
Hi

Yes there are some issue on compiling, unfortunately this is inherited from the original gr-aistx forked on github.

the solution pointed above should work.

The way I did it is to modify the .c/.cpp files after the make fails in the build directory, where gnuradio_swig_bug_workaround.h is included with the right directory (if I remember correctly is "include <gnuradio/swig/gnuradio_swig_bug_workaround.h>" instead of simply gnuradio_swig_bug_workaround.h

after that you rerun make and it should find everything.

**Comment by ghost** [comment]
I was able to fix this issue by adding 
`${GNURADIO_RUNTIME_INCLUDE_DIRS}/gnuradio/swig`
at line 114 of gr-aistx/CMakeLists.txt 

feel free to see what I did here: https://github.com/zhudsonSM/ais

**Comment by caoba1** [comment]
thank you prisemut, worked on debian! i

**Comment by embyte0** [comment]
Great, this should work now.
